export const INCREMENT_ENTHUSIASM = '@@COUNTER/INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = '@@COUNTER/DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;


export const INIT_FECTCH = '@@PRICE_API/INIT_FETCH';
export type INIT_FECTCH = typeof INIT_FECTCH;

export const SUCCESSFUL_PRICE_LIST_FETCH = '@@PRICE_API/SUCCESSFUL_PRICE_LIST_FETCH';
export type SUCCESSFUL_PRICE_LIST_FETCH = typeof SUCCESSFUL_PRICE_LIST_FETCH;

export const SUCCESSFUL_LIST_NAME_FETCH = '@@PRICE_API/SUCCESSFUL_LIST_NAME_FETCH';
export type SUCCESSFUL_LIST_NAME_FETCH = typeof SUCCESSFUL_LIST_NAME_FETCH;

export const FAILED_FETCH = '@@PRICE_API/FAILED';
export type FAILED_FETCH = typeof FAILED_FETCH;

export const UPDATE_SEARCH_TEXT = '@@PRICE_LIST/UPDATE_SEARCH_TEXT';
export type UPDATE_SEARCH_TEXT = typeof UPDATE_SEARCH_TEXT;

export const UPDATE_SELECTED_LIST = '@@PRICE_LIST/UPDATE_SELECTED_LIST';
export type UPDATE_SELECTED_LIST = typeof UPDATE_SELECTED_LIST;