export const INCREMENT_ENTHUSIASM = '@@COUNTER/INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = '@@COUNTER/DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;


export const INIT_FECTCH = '@@PRICE_API/INIT_FETCH';
export type INIT_FECTCH = typeof INIT_FECTCH;

export const SUCCESSFUL_FETCH = '@@PRICE_API/SUCCESSFUL';
export type SUCCESSFUL_FETCH = typeof SUCCESSFUL_FETCH;

export const FAILED_FETCH = '@@PRICE_API/FAILED';
export type FAILED_FETCH = typeof FAILED_FETCH;

