export const REQUEST_LOGIN = '@@LOGIN_API/REQUEST_LOGIN';
export type REQUEST_LOGIN = typeof REQUEST_LOGIN;

export const LOGIN_SUCCESSFUL = '@@LOGIN_API/LOGIN_SUCCESSFUL';
export type LOGIN_SUCCESSFUL = typeof LOGIN_SUCCESSFUL;

export const LOGIN_FAILED = '@@LOGIN_API/LOGIN_FAILED';
export type LOGIN_FAILED = typeof LOGIN_FAILED;

