export const SUCCESSFUL_PRICE_LIST_FETCH = '@@MANAGE_API/SUCCESSFUL_PRICE_LIST_FETCH';
export type SUCCESSFUL_PRICE_LIST_FETCH = typeof SUCCESSFUL_PRICE_LIST_FETCH;

export const SUCCESSFUL_LIST_NAME_FETCH = '@@MANAGE_API/SUCCESSFUL_LIST_NAME_FETCH';
export type SUCCESSFUL_LIST_NAME_FETCH = typeof SUCCESSFUL_LIST_NAME_FETCH;

export const SUCCESSFUL_DATES_FETCH = '@@MANAGE_API/SUCCESSFUL_DATES_FETCH';
export type SUCCESSFUL_DATES_FETCH = typeof SUCCESSFUL_DATES_FETCH;

export const SUCCESSFUL_LAST_DATE_FETCH = '@@MANAGE_API/SUCCESSFUL_LAST_DATE_FETCH';
export type SUCCESSFUL_LAST_DATE_FETCH = typeof SUCCESSFUL_LAST_DATE_FETCH;

export const INIT_LAST_DATE_FETCH = '@@MANAGE_API/INIT_LAST_DATE_FETCH';
export type INIT_LAST_DATE_FETCH = typeof INIT_LAST_DATE_FETCH;

export const FAILED_FETCH = '@@MANAGE_API/FAILED';
export type FAILED_FETCH = typeof FAILED_FETCH;

export const UPDATE_SEARCH_TEXT = '@@MANAGE_API/UPDATE_SEARCH_TEXT';
export type UPDATE_SEARCH_TEXT = typeof UPDATE_SEARCH_TEXT;

export const UPDATE_SELECTED_LIST = '@@MANAGE_API/UPDATE_SELECTED_LIST';
export type UPDATE_SELECTED_LIST = typeof UPDATE_SELECTED_LIST;

export const UPDATE_SELECTED_DATE = '@@MANAGE_API/UPDATE_SELECTED_DATE';
export type UPDATE_SELECTED_DATE = typeof UPDATE_SELECTED_DATE;

export const INIT_LIST_UPLOAD = '@@MANAGE_API/INIT_LIST_UPLOAD';
export type INIT_LIST_UPLOAD = typeof INIT_LIST_UPLOAD;

export const LIST_UPLOAD_SUCCESSFUL = '@@MANAGE_API/LIST_UPLOAD_SUCCESSFUL';
export type LIST_UPLOAD_SUCCESSFUL = typeof LIST_UPLOAD_SUCCESSFUL;

export const START_EDITING = '@@MANAGE_API/START_EDITING';
export type START_EDITING = typeof START_EDITING;

export const STOP_EDITING = '@@MANAGE_API/STOP_EDITING';
export type STOP_EDITING = typeof STOP_EDITING;

export const DELETE_LIST = '@@MANAGE_API/DELETE_LIST';
export type DELETE_LIST = typeof DELETE_LIST;

export const DELETE_LIST_SUCCESSFUL = '@@MANAGE_API/DELETE_LIST_SUCCESSFUL';
export type DELETE_LIST_SUCCESSFUL = typeof DELETE_LIST_SUCCESSFUL;

export const CLEAR_EDITING_DATE = '@@MANAGE_API/CLEAR_EDITING_DATE';
export type CLEAR_EDITING_DATE = typeof CLEAR_EDITING_DATE;

export const INIT_LIST_TYPE_FETCH = '@@MANAGE_API/INIT_LIST_TYPE_FETCH';
export type INIT_LIST_TYPE_FETCH = typeof INIT_LIST_TYPE_FETCH;

export const LIST_TYPE_FETCHED = '@@MANAGE_API/LIST_TYPE_FETCHED';
export type LIST_TYPE_FETCHED = typeof LIST_TYPE_FETCHED;