export const INIT_FECTCH = "@@SALES/INIT_FETCH";
export type INIT_FECTCH = typeof INIT_FECTCH;

export const SUCCESSFUL_SALES_FETCH = "@@SALES/SUCCESSFUL_SALES_FETCH";
export type SUCCESSFUL_SALES_FETCH = typeof SUCCESSFUL_SALES_FETCH;

export const SUCCESSFUL_DATES_FETCH = "@@SALES/SUCCESSFUL_DATES_FETCH";
export type SUCCESSFUL_DATES_FETCH = typeof SUCCESSFUL_DATES_FETCH;

export const SELECT_DATE = "@@SALES/SELECT_DATE";
export type SELECT_DATE = typeof SELECT_DATE;

export const FAILED_FETCH = "@@SALES/FAILED";
export type FAILED_FETCH = typeof FAILED_FETCH;

export const ADD_SALE = "@@SALES/ADD_SALE";
export type ADD_SALE = "@@SALES/ADD_SALE";

export const DELETE_SALE = "@@SALES/DELETE_SALE";
export type DELETE_SALE = "@@SALES/DELETE_SALE";
